### ISSUE TITLE
not generating MCMOT.yaml

### ISSUE THREAD

**Issue by MeowOhMeow** [ricky-696/AICup_MCMOT_Baseline#1]
utils/AICUP_to_YOLOv8.py does not generate MCMOT.yaml to designated location. Should we implement by ourselves, or this is a bug?

**Comment by ricky-696** [comment]
@MeowOhMeow I have added `MCMOT.yaml` to [AICup_MCMOT_Baseline/train_YOLO](https://github.com/ricky-696/AICup_MCMOT_Baseline/tree/main/train_YOLO), thanks.
