### ISSUE TITLE
AICUP_to_YOLOv8.py中的第45行

### ISSUE THREAD

**Issue by Ting0887** [ricky-696/AICup_MCMOT_Baseline#2]
反斜線在windows上會無法讓程式正確執行，
所以如果要在windows上執行，
需改成雙斜線
![image](https://github.com/ricky-696/AICup_MCMOT_Baseline/assets/57065036/f37c6c8e-40fc-4605-9f49-12f23aa58145)

**Comment by ricky-696** [comment]
@Ting0887 感謝糾正，已經把相關程式修改成通用的os分隔符號，如有發現相同問題，再請你發相關issue~

https://github.com/ricky-696/AICup_MCMOT_Baseline/blob/6976c2b07e199d6a2bc4a2b9ed0ca32095e6938d/utils/AICUP_to_YOLOv8.py#L45

https://github.com/ricky-696/AICup_MCMOT_Baseline/blob/6976c2b07e199d6a2bc4a2b9ed0ca32095e6938d/detect.py#L62

https://github.com/ricky-696/AICup_MCMOT_Baseline/blob/6976c2b07e199d6a2bc4a2b9ed0ca32095e6938d/utils/AICUP_to_MOT15.py#L42
